# Generated by Django 5.2 on 2025-10-08 10:37

import account.util.helper
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, default=None, error_messages={'unique': 'کاربر با این شماره ملی قبلا ثبت شده است.'}, max_length=11, null=True, unique=True, validators=[account.util.helper.validate_national_id])),
                ('cellphone', models.CharField(error_messages={'unique': 'This mobile number is already registered.'}, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{9,15}$')])),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
    ]
